### PR TITLE
extra option to log assigns from Plug struct 

### PR DESCRIPTION
**Pull request by mindreframer**
+ removes timex
+ fixes a problem with URLs and explicit ports, like: https://my-website:8888/

### CODE REVIEW

**Comment by gamache** [comment]
Hi!  Thanks for the contributions.  I'm very happy to get rid of Timex as a dependency, and the bugfix around DSN port handling is much appreciated.

Your patches to the handling of the `extra` field, however, seem to be in conflict with what the Sentry API docs specify, namely that the `extra` field should hold arbitrary key/value data to attach to the request: https://docs.sentry.io/hosted/clientdev/attributes/

For that reason, I can't merge this code directly, but I will integrate the parts I can use.

Tip: it's easier for a project maintainer to handle changes when they are broken into separate PRs, without things like non-essential dependency updates and whitespace opinions.  All the same, thank you for improving this code!

**Comment by mindreframer** [comment]
@gamache Hi! Thanks for considering merging the changes! 

I dont quite understand, why there is a conflict with the Sentry API....
We just put a map into the extra field, and that is exactly what the sentry API specifies: 

> An arbitrary mapping of additional metadata to store with the event.
```
{
  "extra": {
    "my_key": 1,
    "some_other_value": "foo bar"
  }
}
```

And this is the data structure, that we return: 

```
iex(1)> Map.take(%{a: 1, b: 2, c: 3}, [:a, :b] )
%{a: 1, b: 2}
```

What else would you expect in the `extra` field?

**Comment by gamache** [comment]
Added in 0.6.3:

Fix handling of port numbers in DSN URL e0439796d020381bcb42e2dcaab484464155f11c
replaced Timex with custom ExSentry.Utils.datetime_now 800dfafe14369911f16c7bb233c22437aa9b13ba

**Comment by gamache** [comment]
I agree that this patch sends a map to the Sentry API under the `extra` field, as is proper.  The part I disagree with is that `ExSentry.Plug.handle_errors`' `opts[:extra]` was repurposed from an arbitrary key/value field that gets passed along to Sentry unharmed, to an index into the `conn[:assigns]` struct.

I would consider this change if something other than `opts[:extra]` were used for this purpose, perhaps `opts[:extra_assigns]` or `opts[:add_assigns_to_extra]`, but I can't give up the `opts[:extra]` field.

**Comment by mindreframer** [comment]
@gamache I see. So `extra_assigns` would be ok, right? )))

**Comment by gamache** [comment]
Yes, that sounds fine. :)

**Pull request closed without merging**
